export const ROLES = {
  ADMIN: "ADMIN",
  FRONTDESK: "FRONTDESK",
  NURSE: "NURSE",
  DOCTOR: "DOCTOR",
  PATIENT: "PATIENT",
};

export const PERMISSIONS = {
  MANAGE_FORMS: "MANAGE_FORMS",
  MANAGE_RULES: "MANAGE_RULES",
  VIEW_REPORTS: "VIEW_REPORTS",
  MANAGE_PATIENTS: "MANAGE_PATIENTS",
};

export const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

